version: "3.9"
services:
  backend:
    image: "denihax/springboot-react-fullstack:3.5.2022.18.46.41"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
