version: "3.9"
services:
  backend:
    image: "denihax/springboot-react-fullstack:27.4.2022.19.31.25"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
